### ISSUE TITLE
Error: getProviderState: Connection controller was not initialized

### ISSUE THREAD

**Issue by ilyar** [broxus/everscale-standalone-client#1]
Uncaught (in promise) Error: Everscale provider was not found
Error: getProviderState: Connection controller was not initialized
![image](https://user-images.githubusercontent.com/761285/163597078-b59c0ac2-1d2e-4583-8869-687f2db53d7f.png)
![image](https://user-images.githubusercontent.com/761285/163597126-fbaa8469-f83b-476d-a94c-669bf681d7f9.png)
https://everscaleguild.github.io/everscale-standalone-client/
**Expect**
![image](https://user-images.githubusercontent.com/761285/163597175-90650f00-d850-4526-8994-481c5c8f842b.png)

**Comment by Rexagon** [comment]
Fixed in [`everscale-inpage-provider:0.3.11`](https://github.com/broxus/everscale-inpage-provider/commit/41237e14ae5f30b6bd81473ebccf44311c011e45) and [`everscale-standalone-client:1.0.4`](https://github.com/broxus/everscale-standalone-client/commit/374020bada3ac6038eb9c67273399ef983a04db1). Please update both dependencies to the latest version.
